export const products = [
  {
    id: 1,
    name: "Mate artesanal",
    category: "Mates",
    price: 15000,
    image: "https://placehold.co/600x600/f4e9e5/8d5966?text=Mate",
    description:
      "Mate artesanal ideal para regalar o disfrutar todos los días.",
    featured: true,
    promotion: false,
  },
  {
    id: 2,
    name: "Termo premium",
    category: "Termos",
    price: 35000,
    image: "https://placehold.co/600x600/f4e9e5/8d5966?text=Termo",
    description: "Termo de excelente calidad para acompañarte en cada momento.",
    featured: true,
    promotion: false,
  },
  {
    id: 3,
    name: "Taza especial",
    category: "Tazas",
    price: 12000,
    image: "https://placehold.co/600x600/f4e9e5/8d5966?text=Taza",
    description: "Una taza especial para regalar o disfrutar en casa.",
    featured: true,
    promotion: false,
  },
  {
    id: 4,
    name: "Set matero",
    category: "Regalería",
    price: 42000,
    image: "https://placehold.co/600x600/f4e9e5/8d5966?text=Set",
    description: "Set ideal para regalar a esa persona especial.",
    featured: true,
    promotion: false,
  },
  {
    id: 5,
    name: "Mate rosa",
    category: "Mates",
    price: 18000,
    image: "https://placehold.co/600x600/f4e9e5/8d5966?text=Mate+Rosa",
    description: "Mate con una estética delicada y especial.",
    featured: false,
    promotion: false,
  },
  {
    id: 6,
    name: "Combo regalo",
    category: "Promociones",
    price: 50000,
    image: "https://placehold.co/600x600/f4e9e5/8d5966?text=Combo",
    description: "Una combinación especial para sorprender.",
    featured: false,
    promotion: true,
  },
];
